spring.application.name=grades-api

# Conexion base de datos local
spring.datasource.url=jdbc:postgresql://localhost:5432/grades_db
spring.datasource.username=admin
spring.datasource.password=admin1234

# "update" creara las tablas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto servidor backend
server.port=8080

# Agregamos este codigo para que se ejecute el script de la base de datos
spring.sql.init.mode=always

spring.jpa.defer-datasource-initialization=true